require:
  - standard
  - rubocop-rake
  - rubocop-rspec
  - rubocop-performance

inherit_mode:
  merge:
    - Exclude

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - bin/**/*
    - sig/**/*

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

RSpec:
  Enabled: true
